export const CODE_TO_NAME: Record<string, string> = {
  I78: 'activeDataSources',
  T0: 'backupStatus',
  MN: 'computerName',
  AR: 'customer',
  AN: 'deviceName',
  OT: 'deviceType',
  T7: 'errors',
  TB: 'last28Days',
  TL: 'lastSuccessfulSession',
  YV: 'lsvStatus',
  OP: 'profile',
  PN: 'retentionPolicy',
  T3: 'selectedSize',
  YS: 'storageStatus',
  TM: 'totalM365BillableUsers',
  US: 'usedStorage',
  RVB: 'virtualDisasterRecoveryDataColorBarLast28Days',
};
